name = "Create Customised"
author = "AdoLovesChicken"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ada42667b8c7ce1b195e7b0ddd08eee656e7b737185b022acd99c2a98df0d73e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
