name = "Create Customised"
author = "AdoLovesChicken"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eedf7f5b40809097958278d5865a78b59da581b5dc2830a5921fec3626deac3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
